server:
  port: 8888

logging:
  level:
    root: info
    org:
      springframework:
        security: info
        web: debug
    springfox: debug
    com.sublink.hanzool: debug

spring:
  devtools:
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        format:
          sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testlocal
      username: user
      password: pass
